### ISSUE TITLE
faiss

### ISSUE THREAD

**Issue by wanghaisheng** [willard-yuan/CNN-for-Image-Retrieval#11]
大神有没有评估过[faiss](https://github.com/facebookresearch/faiss)在处理咱这一系列绕着image retrieval的工作中有多大实际的提升吗

**Comment by willard-yuan** [comment]
faiss只是做的一个索引，在image retrieval上决定精度的还是feature，你这里的提升只的是哪个方面？

**Comment by wanghaisheng** [comment]
那我理解 咱这个仓库重点是如何提取feature的算法对比

**Comment by willard-yuan** [comment]
是的，这个项目主要对使用CNN做检索的一个示例~

**Comment by duchengyao** [comment]
我把作者的模型换成了 resnet-50 和 faiss ，在2000W数据库效果差不多可以达到0.01秒一张图

**Comment by wanghaisheng** [comment]
@duchengyao 分享一下？

**Comment by duchengyao** [comment]
https://github.com/duchengyao/flask-keras-cnn-image-retrieval

最新的版本不方便发布，这个你看能不能跑通
