### ISSUE TITLE
>> extractCNN boost::filesystem::canonical  我遇到这个问题　　请指导！

### ISSUE THREAD

**Issue by sunyinhui** [willard-yuan/CNN-for-Image-Retrieval#2]

**Comment by willard-yuan** [comment]
怎么还有boost这个库？你把详细的错误信息贴出来，另外把你的matlab版本也跟我说一下

**Comment by sunyinhui** [comment]
Matlab2015b 
![extractcnn](https://cloud.githubusercontent.com/assets/6357309/12029174/6e209004-ae1f-11e5-82af-823b000160ca.png)

**Comment by willard-yuan** [comment]
你用matconvnet1.0-beta14试试，即把那个`run xxx`的改成matconvnet1.0-beta14。如果这样还不行的话，确认一下你的matconvnet是否可以使用。

**Comment by sunyinhui** [comment]
这个可能是我把　clear all;close all;clc;　注释的缘故　 ^~^
没动代码　又出现一下bug
![matconvnet-1 0-beta14](https://cloud.githubusercontent.com/assets/6357309/12030256/190ae89a-ae37-11e5-8508-054a5741d129.png)

**Comment by sunyinhui** [comment]
错误使用 vl_simplenn (line 252)
Unknown layer type lrn

出错 extractCNN (line 45)
       res = vl_simplenn(net, im_) ;

**Comment by willard-yuan** [comment]
这个问题应该不是这个代码的原因引起的，而是可能是你没正确安装matconvnet所引起的，你可以加我qq: 874422491, 我远程帮你解决一下。

**Comment by sunyinhui** [comment]
谢谢啦, 换成MatConvNet1.0-17bate 可以运行
