### ISSUE TITLE
blog打开不了

### ISSUE THREAD

**Issue by HeGaoYuan** [willard-yuan/CNN-for-Image-Retrieval#4]
你好，
       我打开你readme里面的link想看看对应的blog，但是打开不了

**Comment by willard-yuan** [comment]
@HeGaoYuan 可以暂时先直接看[图像检索：CNN卷积神经网络与实战](https://github.com/willard-yuan/willard-yuan.github.io/blob/master/_posts/2015-04-02-CBIR-CNN-and-practice.md)，这个就是原来的博文，之所以把博客撤下，是想重新把博文整理一下。

**Comment by HeGaoYuan** [comment]
好的，谢谢了
加油，会继续支持你的研究
