### ISSUE TITLE
queryInDatabaseDemo里的256feat2048Norml.mat或者256feat4096Norml.mat需要自己生成吗？

### ISSUE THREAD

**Issue by brisker** [willard-yuan/CNN-for-Image-Retrieval#5]
请问博主queryInDatabaseDemo里的256feat2048Norml.mat或者256feat4096Norml.mat需要自己生成吗？自己改extractCNN这个文件？

**Comment by willard-yuan** [comment]
@brisker 这个保存特征的文件是用extractCNN.m脚本提取的，你可以用这个extractCNN.m在自己的图像库上提取特征，然后用这个queryInDatabaseDemo.m进行检索查询，把256feat4096Norml.mat改成相应的文件即可，具体请看[L68](https://github.com/willard-yuan/CNN-for-Image-Retrieval/blob/master/extractCNN.m#L68).
