### ISSUE TITLE
retrieval_virsulazation.m建议计算score用矩阵相乘,图像几十万张的时候会快很多

### ISSUE THREAD

**Issue by piaobuliao** [willard-yuan/CNN-for-Image-Retrieval#6]
tools/retrieval_virsulazation.m

% %for loop = 1:n
% %    VecTemp = featNorm(loop, :);
% %    score(loop) = QueryVec*VecTemp';
% %end

score = (QueryVec*featNorm')';

用了http://www.vlfeat.org/matconvnet/pretrained/下的vgg-m-1024模型提取特征,CPU差不多一秒钟5张,GPU(GTX970)快了不少一秒钟50张左右

**Comment by willard-yuan** [comment]
@piaobuliao 用矩阵相乘代替循环确实会加速计算，已经在相应的地方修改，非常谢谢指出。
