### ISSUE TITLE
You might be interested in Deep Video Analytics

### ISSUE THREAD

**Issue by ghost** [willard-yuan/CNN-for-Image-Retrieval#7]
Hey, saw your repo and blog about visual search. 
You might be interested in my project Deep Video Analytics.
Which implements full fledged visual search and data analytics engine. 

https://github.com/AKSHAYUBHAT/DeepVideoAnalytics/

**Comment by willard-yuan** [comment]
Yeah, I have given a star to the repo. By the way, for image retrieval, which method do you use?

**Comment by ghost** [comment]
I have an extensible framework, currently the query / indexing is done by inception v3 and facenet, though I am using exact L2 distance for search, I am very close to implementing Yahoo/ FLICKR LOPQ (its currently implemented as clustering method).
