### ISSUE TITLE
PicSearch demo?

### ISSUE THREAD

**Issue by anxingle** [willard-yuan/CNN-for-Image-Retrieval#9]
楼主您好，请问您博客中的Pic Search 的demo- “CNN-Web-Demo-for-Image-Retrieval”. 还开放吗？ 链接好像失效了.....也没有找到，不知道可否发一下链接呢?   谢谢。

**Comment by willard-yuan** [comment]
@anxingle 我把web的代码放在这里了，[web](https://github.com/willard-yuan/CNN-for-Image-Retrieval/tree/master/web)，修改一下路径就可以在本地跑起来。
